// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250528195928_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Absolutely Nothinggg",
                            Created = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Did Nothing"
                        },
                        new
                        {
                            Id = 2,
                            Content = "But did absolutely Nothinggg",
                            Created = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Tried something"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Wait still did Nothinggg",
                            Created = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Finally Something"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
